### ISSUE TITLE
BUG: When the first item is a finished task

### ISSUE THREAD

**Issue by mariomui** [lumoe/obsidian-rollover-daily-todos#123]
```
---
Aliases:
---


- [x] Ldkjfdkjfd
	- [ ] testing
		- [x] testing 

- [ ] dkfjdkfj
- [ ] dkfjdkfjd
	- [x] kfdjkfjd

dkdjfdkjfdjf
```
Before:
![Screenshot 2023-10-14 at 10 30 50 PM](https://github.com/lumoe/obsidian-rollover-daily-todos/assets/29618692/4e5d34b7-678c-490d-95da-02dd76004686)

After:
![Screenshot 2023-10-14 at 10 30 26 PM](https://github.com/lumoe/obsidian-rollover-daily-todos/assets/29618692/62299c02-fbf7-47ef-bd9e-0315ab53dfa1)

The resulting first item in the new note causes the following notes to be misaligned.

The Settings are:
   deleteOnComplete: True;
    removeEmptyTodos: false;
    rolloverChildren: true;
    rolloverOnFileCreate: true;

**Comment by lumoe** [comment]
Can you please describe the exact desired behaviour? Is it indentation?
