### ISSUE TITLE
Exclude certain headers?

### ISSUE THREAD

**Issue by marcellonovak** [lumoe/obsidian-rollover-daily-todos#137]
I have a daily todos list, but also a repeating daily checklist for things like showering and taking my meds - that don't need to be rolled over. Is there a way to exclude certain checkboxes from being rolled over?

**Comment by CaptainDario** [comment]
I am also interested in this.

It would be nice if there were a way to exclude/include only certain headings.

**Comment by marcellonovak** [comment]
posted an updated issue
