### ISSUE TITLE
Blank Settings - Solution: remove spaces in template path

### ISSUE THREAD

**Issue by usizu** [lumoe/obsidian-rollover-daily-todos#29]
I'd like to use the "Delete todos from previous day" feature, and if i understood correctly it should be accessible from the settings screen from Obsidian preferences Plugin Options, however that screen is totally blank for me when I select the plugin. There are no plugin settings loading for me for this plugin it seems. Is this normal?

![image](https://user-images.githubusercontent.com/32371934/132139762-f4b431c9-1ec7-4978-aeaa-35a12092a8fc.png)

**Comment by KjellConnelly** [comment]
Seems like a bug. Could you open the developer console and take a peek for me? It's showing for me.

**Comment by usizu** [comment]
This gets printed in console when i click on the plugin settings:

```
Uncaught (in promise) TypeError: Cannot read property 'path' of null
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
    at o (app.js:1)
    at t.read (app.js:1)
    at RolloverSettingTab.getTemplateHeadings (eval at <anonymous> (app.js:1), <anonymous>:630:51)
    at RolloverSettingTab.display (eval at <anonymous> (app.js:1), <anonymous>:636:41)
    at t.openTab (app.js:1)
```

**Comment by KjellConnelly** [comment]
Hmmm... do you have the `Daily Notes` plugin, or the `Periodic Notes` plugin installed and enabled? If so, do you also have a template set for them? There should probably be some sort of check for this, but that's my best guess for now.

**Comment by usizu** [comment]
I use the Periodic notes plugin.. there is only a template set for Daily, not for the weekly or monthly. I just tried giving them a template in the Periodic notes settings but same behaviour still

**Comment by KjellConnelly** [comment]
Can you take a screenshot of your periodic or daily note settings? Here's a screenshot of what mine look like, and a screenshot of what the Rollover Plugin should look like

<img width="1904" alt="Screen Shot 2021-09-05 at 9 29 51 PM" src="https://user-images.githubusercontent.com/13230597/132160912-88d99d02-fe22-4e12-971e-f8d3843f6731.png">

<img width="1904" alt="Screen Shot 2021-09-05 at 9 29 57 PM" src="https://user-images.githubusercontent.com/13230597/132160932-c4eeaf4c-858a-41b7-9fa2-bc3d874cfb45.png">

**Comment by usizu** [comment]
![image](https://user-images.githubusercontent.com/32371934/132172439-aed5b3a0-18c2-43b5-ace8-a61ca2a061ac.png)

I tried toggling off weekly and monthly but no effect either.

And the rollover settings just to confirm:

![image](https://user-images.githubusercontent.com/32371934/132172539-b78a38e5-6716-4b06-891a-0cde1cb06503.png)

**Comment by usizu** [comment]
Ok so I turned off the Periodic notes plugin and the Rollover settings are showing now. I tested and the "Delete todos from previous day" setting is now working as expected.

However there is no template to select for Template headings, even though I do have a Daily Note Template in the Periodic plugin: 
![image](https://user-images.githubusercontent.com/32371934/132173230-ee74a211-a684-4c4c-a315-bc0f635e22da.png)


And incase its relevant, the same error message continues to print in the console whenever i click on the Rollover settings in the sidebar.

**Comment by KjellConnelly** [comment]
I'm pretty sure I figured out the problem for you. It's because the plugin can't handle spaces in your template name/path. Try renaming with camelCase or template-dashes or whatever. Should work then. 

Just tested it a bit and for some reason, one of the public obsidian api functions cannot handle files with spaces. I was able to escape the spaces (works on my Mac at least): `path = path.replace(' ', '/ ')`. 

Escaping the path allowed me to locate the template file, but for some reason I can't read the contents of the file using their `vault.read()` function. I'll take a look at it later when I got more time.

**Comment by usizu** [comment]
i removed the space and that did the trick. thanks for the help. i guess thats good enough of a solution on my end

**Comment by KjellConnelly** [comment]
I just tried messing around with some things and I got the bug happening, but something I did made it go away without actually changing any code. I'm guessing something to do with actually changing the path to the template. I turned off `Periodic Notes`, and turned on `Daily Notes`, and fiddles with some different templates, and then went back to `Periodic Notes` and messed with paths again. For some reason, it was able to detect the template file properly (even when it had spaces in it) after that. Not exactly sure how to fix it for now, so I'll just pin this thread for others who come here for now.

**Comment by dcgk** [comment]
Hi! The functionality sounds very interesting as I spend some time doing exactly this task every morning when I create my new Daily Note. 
When I first installed  the rollover plugin, I experienced the blank settings screen. I use Periodic Notes and have no spaces in the path/file names. After turning on and off the Periodic Notes Plugin several times, now the settings screen of Rollover does appear. But I still can not select any template.
What to do?

**Comment by raybaxter** [comment]
I had this problem also. In my case it was because I had the Daily Note template file location configured to `/templates/daily_template.md` That worked for creating new daily notes, but the to see settings in this plugin required removing the initial `/` from the template file location.
