### ISSUE TITLE
Duplicate Todos being rolled over when using multiple devices

### ISSUE THREAD

**Issue by travipross** [lumoe/obsidian-rollover-daily-todos#35]
I use Obsidian on 3 different devices (Ubuntu Desktop, Ubuntu Laptop, Android Phone), and I synchronize my vault between those devices via [Syncthing](https://syncthing.net/).

Consider the laptop/desktop devices for now, just to remove Android from the equation: When I create a new daily note on my desktop, the Todos from the previous day correctly roll over. However, if I wait for the files to sync and I open the same file in Obsidian on my laptop, the rollover is triggered again. If I don't happen to notice this right away, it results in the entire set of Todos being duplicated in the current daily note. 

I've experimented with this on my mobile device too and observed the same thing. It seems odd to me that the rollover is triggered when opening the existing note, rather than just when the note is first created on a given device.

I've observed some other quirks like my [creation dates not properly by synchronized by Syncthing](https://forum.syncthing.net/t/feature-request-sync-creation-times-dates/9184), but I is this metadata used by this plugin when doing an automatic rollover? If so, should there not be some sort of indicator that a sync already took place anyway?

**Comment by lumoe** [comment]
Hi @travipross, thank you for your report. I am also using Syncthing and I have never experienced this behaviour.
Can you confirm that this is still happening?

**Comment by travipross** [comment]
Hi @lumoe, I submitted this over a year ago now and with a few updates since then, it appears the problem is resolved. I repeated my documented steps from back then and wasn't able to trigger the same unexpected behaviour. 

Closing this issue now. Thanks for the follow-up nonetheless!
