### ISSUE TITLE
[FR] Compatibility with Tasks plugin 📅 date format, change date on rollover 

### ISSUE THREAD

**Issue by Zebrazilla** [lumoe/obsidian-rollover-daily-todos#51]
I'm using this in conjunction with the [Tasks ](https://github.com/obsidian-tasks-group/obsidian-tasks) plugin. I always make sure to set a date on any task in a daily note, so that any task that hasn't been rolled over can be surfaced as overdue, but also to list upcoming tasks etc.

When rolling over tasks in a daily note that is formatted with date, the date isn't changed and as such will appear wrong if queried. In my case I pull in tasks using Tasks plugin from other notes with this date, and a such a rolled over task with date formatting will still appear in the daily note, even if it now lives in the daily note it rolled over to.

My request is therefore if it would be possible to look for 📅 YYYY-MM-DD in a task when rolling over, and if found, change it to the date that the daily note has which it is rolling over into.

_Thanks for a great plugin!_

**Comment by lumoe** [comment]
Hi @Zebrazilla, thank you for your FR. 
I don't think this is a good idea as it leads to strange behaviour. I use the _Tasks_ plugin as well and I e.g. use the daily note to collect ToDos that might be in the future. So if the plugin starts to manipulate the information contained in the ToDo the risk of loosing important information is too high. For that reason, we will never manipulate the content of the ToDo.
