### ISSUE TITLE
Todos roll over twice

### ISSUE THREAD

**Issue by michaelcaterisano** [lumoe/obsidian-rollover-daily-todos#52]
Hi! Thanks for creating an awesome plugin. It usually works great, but lately I've noticed an issue where when I open a new daily note, todos roll over twice, i.e. create duplicates. So the previous day's list will end up looking like this on the current note:

```
- todo1
- todo2
- todo3
- todo1
- todo2
- todo3
```

I'm using Obsidian on three devices and wondering if maybe I'm encouraging some weird syncing problems by doing so. Any thoughts would be appreciated!

**Comment by kumekay** [comment]
I experience the same problem, I sync my vault using Syncthing on 3 devices

**Comment by sauld95** [comment]
I found that the sync app "DriveSync" works perfect for Obsidian. If I update on the computer and later update on my mobile phone, they will merge together without any conflicts. I noticed it will actually create a copy of the markdown file if there come across any conflicts between both files. for example "Note 1 Conflict 07/30/22"

**Comment by bobonthenet** [comment]
I am also having this problem and agree it is definitely a sync issue. 

To reproduce:
1. Have a note from the previous day with todos that will rollover.
2. Create a new daily note and observe as todos rollover.
3. On a second device allow your notes to sync then open your daily note. Observe as todos rollover a second time.

If syncing is automatic you can also run into the issue of the duplicates syncing to the original device.

**Comment by bobonthenet** [comment]
So I've been thinking about this and I think I can provide a solution. I would wrap it in a new setting to make in an option just in case for some reason someone doesn't want this behavior. I would basically just get the todos that already exist in today's note and remove them from the notes to be rolled over array, before finally applying them to today's note. I've never worked on an Obsidian plugin before so I'm not sure how long this would take me but I'm sure I could have it done before Monday either way. Does this seem like it'd be a good solution for this issue and would a PR for this change be appreciated?

**Comment by lumoe** [comment]
Hi @bobonthenet, thank you for your detailed description. I personally use Syncthing as well, but never experienced this behaviour. To be fair, I never use the device **exactly** in the same time.

In its current state, I do not think, that the plugin should solve issues that are related to sync issues.

**Comment by bobonthenet** [comment]
I still think this would be a nice option as a setting. I also see the problem where the daily note is created from a template with pre-existing todos. When the rollover happens it can create duplicate todos. That said, I guess I agree that this plugin shouldn't try to solve problems based on other plugins. I just think this new functionality might be nice to have on it's own and not as a solution to this particular issue.

**Comment by npolanosky** [comment]
I've just encountered this as well- Would it be practical to have it simply detect duplicates and not copy any entries which are identical?
