### ISSUE TITLE
Rollover from PREVIOUS Daily note, not 'Yesterday' only.

### ISSUE THREAD

**Issue by MartynKeigher** [lumoe/obsidian-rollover-daily-todos#53]
I work Mon - Fri, and I love making Daily ToDo lists. During the week, my incomplete notes from (for e.g.) Tuesday to Wednesday roll over just fine, but any incomplete ToDo's from a Friday, will not roll over to a Monday (of the following week) as technically... Friday was not "yesterday".

Would be nice if this plugin had an option to allow you to rollover incomplete notes from the 'previous daily note'... instead of strictly "yesterday" only.

**Comment by lumoe** [comment]
FWIW, this should be possible. Can you verify the behaviour @MartynKeigher?

**Comment by tim-hilt** [comment]
I think this can be closed. OP didn't answer and the current logic always just takes the last daily note into account:

https://github.com/lumoe/obsidian-rollover-daily-todos/blob/master/src/index.js#L92-L97

**Comment by obbardc** [comment]
Yep, it works as expected
