### ISSUE TITLE
Ownership Request

### ISSUE THREAD

**Issue by ovo-saxon-zerbino** [lumoe/obsidian-rollover-daily-todos#60]
@shichongrui I can see you've recently updated the README to indicate this is no longer supported, I was hoping you'd be willing to transfer ownership to myself.

I was looking to fork the repo anyway as I'd like to attempt to solve rolling todos over under subheadings & supporting directories in the file path for my own use case. While I've not owned an OS project like this before I believe I'd be able to support reasonably well and as someone that uses it daily it's in my best interest to try and keep this up to date 😄

**Comment by shichongrui** [comment]
@ovo-saxon-zerbino thanks for the interest. Another person has already requested ownership so I'm going to be transferring ownership to him unless he changes his mind. I'm just waiting for him to delete his fork of the repo, which prevents ownership transfer.

If that falls through, you will be next on the list.

**Comment by ovo-saxon-zerbino** [comment]
Understandable, thanks for the quick reply & all the best!

**Comment by lumoe** [comment]
The transfer has worked, thank you for coming up with this idea and creating this project in the first place @shichongrui! 

@ovo-saxon-zerbino these are the exact features I would like to implement as well. If you are still interested in working together, code reviewing or testing out new features, let me know. :-)

**Comment by ovo-saxon-zerbino** [comment]
Hey, that would be good! I've had a bit of a look around the code base but I think there's still some getting up to speed I'll need to do. When I get some time to try that out I will hopefully open a PR if you don't get there before me and we can go from there.

**Comment by lumoe** [comment]
Sounds good! I already did some work with respect to folders in the file path and submitted a PR #57 
It does solve the issue, but I still need to check if this change does have any side effects. Maybe it can give you a starting point for your investigation.
