### ISSUE TITLE
1.1.1 release not working

### ISSUE THREAD

**Issue by dmkravets** [lumoe/obsidian-rollover-daily-todos#69]
I'm on Mac and iOS. Newest update to this plugin breaks functionality

**Comment by javiavid** [comment]
It doesn't work on Windows 11 either.

**Comment by quetza** [comment]
The problem is the building of the paths is which 1.1.1 was supposed to fix is broken in a different way. If you want the quickest fix, edit your ".obsidian/plugins/obsidian-rollover-daily-todos/main.js" file and change line 1013 from:
   `folder == "" ? "/" : ""` 
 to
  `folder == "" ? "/" : "/"`

and then restart Obsidian. 

(I know this is stupid code, but it's optimized for the smallest action to get this working again)

**Comment by finnbru** [comment]
Fixed it - many thanks for quick email.

**Comment by tobiasvl** [comment]
Thank you! This worked for me too.

**Comment by KalenXI** [comment]
Unfortunately that fix didn't work for me on macOS. That resulted in `if (filePathConstructed !== file.path) return;` always returning because then filePathConstructed had an extra / in it.

The fix I found was to change line 971 from:
`const path = file.path.replace(`${folder}/`, '').replace(`.${file.extension}`, '');`
to
`const path = file.path.replace(`${folder}`, '').replace(`.${file.extension}`, '');`

For some reason it seems like one of those functions is expecting the extra / and the other one isn't.

**Comment by avigilante** [comment]
On a Mac, Obsidian 1.0.3, @quetza suggestion worked for me! Thanks!

**Comment by quetza** [comment]
> Unfortunately that fix didn't work for me on macOS. That resulted in `if (filePathConstructed !== file.path) return;` always returning because then filePathConstructed had an extra / in it.
> 
> The fix I found was to change line 971 from: `const path = file.path.replace(`${folder}/`, '').replace(`.${file.extension}`, '');` to `const path = file.path.replace(`${folder}`, '').replace(`.${file.extension}`, '');`
> 
> For some reason it seems like one of those functions is expecting the extra / and the other one isn't.
> 
> I'm also not sure what advantage going through the whole find and replace process has over just using `file.basename` since they both just return the filename without the folder path or extension but maybe I'm missing something.

What happens if you replace line 1013 with this? 
   `folder[folder.length-1] == "/" ? "" : "/"`

It should just add the / if it's not already there.

**Comment by igormoochnick** [comment]
I've had the same issue and I've tried this fix ^^^ and it worked. I didn't try any other fixes
This worked for me:
`folder[folder.length-1] == "/" ? "" : "/"`

**Comment by lumoe** [comment]
Sorry for the inconvenience. I released a new version that should fix the problem. 

Please ping me if something goes wrong!

**Comment by tim-hilt** [comment]
Works for me! Didn't work with 1.1.1

**Comment by 7596ff** [comment]
> If you want the quickest fix ...

Didn't work for me, on 1.1.1 or 1.1.2

Using periodic notes, daily note template is `YYYY/MM/gggg-[W]ww/YYYY-MM-DD`

**Comment by lumoe** [comment]
@7596ff Have you tested it without the fix?

Can you tell what's your path in  "New file location" in the daily note settings?

**Comment by 5aint2ero** [comment]
> > If you want the quickest fix ...
> 
> Didn't work for me, on 1.1.1 or 1.1.2
> 
> Using periodic notes, daily note template is `YYYY/MM/gggg-[W]ww/YYYY-MM-DD`

I have the same problem. Im using "Daily notes" with template format YYYY-MM-DD on a Windows machine.

**Comment by lumoe** [comment]
@7596ff @5aint2ero please give the newest version a try and remove your custom patch, this was already solved in 1.1.2.

**Comment by 5aint2ero** [comment]
> 

Sry, I think my reply was a little unclear. I just tried a fresh install of the plugin without any custom patches.

**Comment by 5aint2ero** [comment]
> @7596ff @5aint2ero please give the newest version a try and remove your custom patch, this was already solved in 1.1.2.

Sry, I think my reply was a little unclear. I just tried a fresh install of the plugin without any custom patches.

**Comment by 7596ff** [comment]
1.1.3 also didn't work.
> Can you tell what's your path in "Note folder" in the daily note settings?
<img width="795" alt="image" src="https://user-images.githubusercontent.com/1760581/205220320-acbcce8d-ed25-404d-af04-619a86563f71.png">

What's confusing is that 1.1.1 worked for about a week and a half, and I think december 1st is the first day it didn't.

**Comment by 7596ff** [comment]
It worked today!

**Comment by lumoe** [comment]
I was not able to reproduce the issue with the configuration you provided. I have never encountered an issue with rolling over ToDos right after midnight, I will investigate potential issues and will come back to you with results. 
Good to know, that it does work now though :smiley:

**Comment by 5aint2ero** [comment]
The Version 1.1.3 still isnt working on both of my Windows 10 machines. I tried uninstall and reinstall the plugin and also disable other plugins. Beside the standard plugins commong with obsidian I use "Reminder" and "Day Planner".
