### ISSUE TITLE
Feature Request: Option to roll over todos with their children

### ISSUE THREAD

**Issue by tim-hilt** [lumoe/obsidian-rollover-daily-todos#70]
**Current behavior**

If I roll over something like this

``` markdown
# 2022-11-29

- [x] Something not as important
- [ ] Something important
    - A note for the solution strategy
```

only the open todo-item get's rolled over:

``` markdown
# 2022-11-30

- [ ] Something important
```

even worse: If `Delete todos from previous day` is enabled, the previous daily note looks like this:

``` markdown
# 2022-11-29

- [x] Something not as important
    - A note for the solution strategy
```

which is alters the meaning of the completed todo-item.

**Suggested behavior**

It would be a sensible default (in my opinion), if the plugin only watches the root-level of the markdown-file and rolls over all the todo-items that it finds there *along with their children*:

``` markdown
# 2022-11-29

- [x] Something not as important
- [ ] Something important
    - A note for the solution strategy
```

will result in:

``` markdown
# 2022-11-30

- [ ] Something important
    - A note for the solution strategy
```

If the user doesn't want this behavior, they could still head to the settings and deactivate `roll over todos including children` (which is enabled by default) to get back the previous behavior.

**Comment by lumoe** [comment]
Thank you for your FR and the detailed information you provided. 
In order to avoid duplication, I will close this issue in preference of #41 and add a link to your detailed description.

**Comment by tim-hilt** [comment]
Didn't see that one! Thanks for the info.
