### ISSUE TITLE
Version 1.1.3 Stopped working

### ISSUE THREAD

**Issue by gkowalski** [lumoe/obsidian-rollover-daily-todos#71]
Suddenly my ""Rollover Daily Todo" stopped rolling over anything from the previous day on my Mac . 

Using Obsidian v1.0.3 with Rollover 1.1.3 . 

I also have Teamplater 1.16.0 installed . 

Is this a known issue

**Comment by Y1ng0** [comment]
i also want to know

**Comment by lumoe** [comment]
@gkowalski @Y1ng0 
Can you provide me your exact settings so I can try to reproduce them locally?

**Comment by Y1ng0** [comment]
obsdian version
<img width="245" alt="image" src="https://user-images.githubusercontent.com/69341818/206102159-73c5b281-1c33-4ffe-a856-60a2f95887ce.png">
my template
<img width="576" alt="image" src="https://user-images.githubusercontent.com/69341818/206102450-4179985a-f773-4186-b73b-90fbfd3bb67e.png">
settings
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/69341818/206102505-bbb7d568-055d-469a-a936-01f4aa63ea9d.png">

**Comment by lumoe** [comment]
Please provide the settings of your daily note plugin as well, i.e. folder, daily note file name

**Comment by Y1ng0** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/69341818/206110205-e16fa735-ba9f-46d8-8823-64b8b657510d.png">

**Comment by gkowalski** [comment]
Here is my DailyTemplate.md

[DailyTemplate.md](https://github.com/lumoe/obsidian-rollover-daily-todos/files/10176719/DailyTemplate.md)

**Comment by lumoe** [comment]
This is expected behaviour, the plugin does not support rollover into future daily notes.

It is a feature request on our backlog, that we will hopefully implement in the future.

**Comment by gkowalski** [comment]
I've had it fail on the current day also.  Think it was on a monday , didn't roll over last fridays todos.

**Comment by lumoe** [comment]
My guess at this point would be, that there might be an issue with the `Periodic Notes` plugin which might  interfere with the weekly notes. I need to investigate that further. 

If you encounter the problem again in the future, looking at the developer console of Obsidian and checking out whether there are error messages by the plug-in would be very helpful.

**Comment by gkowalski** [comment]
where do we find the logs for obsidian ?

**Comment by lumoe** [comment]
> If you would like to access developer tools, you can find it in the menu bar (View > Toggle Developer Tools) or use the hotkey (cmd+ option + i on Mac and ctrl + shift + i for Windows).

Source: https://forum.obsidian.md/t/how-to-access-the-console/16703/2

**Comment by ipwnponies** [comment]
If this isn't the same issue as others, I can create a new issue:

```
rollover-daily-todos: 0 todos found in Pasted image 20221212165317.md
```

I recently tried moving attachments to nested sub directory. The default name for attachments uses timestamp (second resolution).
<img width="579" alt="image" src="https://user-images.githubusercontent.com/4278368/207428110-17644244-f946-4fcc-bc46-49886f6268d7.png">

Does this plugin need to look recursively? I use it with "Daily Notes" core plugin, which has a predictable and configurable location to find the previous day's notes.

**Comment by lumoe** [comment]
Thank you for pointing this out @ipwnponies, this was fixed already and will be fixed in the upcoming release.

**Comment by lumoe** [comment]
@gkowalski quick ping to ask whether this issue occured another time. 
If not, please feel free to close this issue.

**Comment by gkowalski** [comment]
Nope , Didn't happened over the weekend.
