### ISSUE TITLE
New note not saved after rollover, resulting in lost tasks

### ISSUE THREAD

**Issue by barryvan** [lumoe/obsidian-rollover-daily-todos#85]
When opening a new daily note, I get the notification that tasks have been rolled over. And indeed, they disappear from the old note and appear in the new. But if I change files (or, I think, open a new tab), then the tasks disappear from the new note. I suspect that it's because the autosave is not being triggered for the new file.

Fortunately my vault is stored in OneDrive, so I can use the version history to restore the tasks, but it's a relatively "suboptimal" situation. ;)

I'm using Periodic Notes rather than the built-in plugin, as well as Templater. I've attached my [_Daily Template.md](https://github.com/lumoe/obsidian-rollover-daily-todos/files/10632225/_Daily.Template.md) just in case it helps. I'm targeting the "Miscellaneous tasks" section.

I don't think the template is causing issues; I've been using this template for a few months now, and the rollover also seems to work fine (albeit without the file being saved!).

**Comment by barryvan** [comment]
So I just started today's new note, and it seems that the tasks didn't roll over at all... At least, I didn't see them, although I did see the little popup telling me it had rolled over six tasks. :/ I wonder if a stopgap solution for this would be an option to disable the automatic rollover, so that I can trigger it manually instead?

**Comment by tim-hilt** [comment]
I think I can make some time today to look into the issue. Can you share a screenshot of your settings for rollover-daily-todos and periodic-notes?

also - have you tried restarting Obsidian? Some users reported that that’s fixed their issues with periodic notes

**Comment by barryvan** [comment]
Sorry for the delay, @tim-hilt! Attached are my settings. I'll close down Obsidian tonight (in fact, I'll do a full restart of my computer)... I have a Windows and Linux background, and I'm normally pretty good about closing (and _quitting_) apps at the end of each day. 😆 

![image](https://user-images.githubusercontent.com/124363/217229453-07599868-38ab-463b-a542-2052a8411517.png)
![image](https://user-images.githubusercontent.com/124363/217229546-58f8bb9e-d4f1-49d7-8005-9b35e60157b8.png)

**Comment by tim-hilt** [comment]
Thanks for the screenshots. I just tried it out and couldn't reproduce it with the default settings. I think it's related to the date-format! Can you try if it works with the default day-format `YYYY-MM-DD`? That would help me find the issue faster.

**Comment by tim-hilt** [comment]
Small update: I think I found the issue. Are you comfortable with installing the plugin off of a branch on GitHub? If so, then you could try installing from fix/complex-date-formats.

**Comment by barryvan** [comment]
Thanks so much for jumping on this so quickly, @tim-hilt! (And for jumping on it at all!)

 I don't have a dev environment on this machine, so I "manually" applied the diff... and it seems to have worked! My todos rolled over beautifully this morning. 🎉

**Comment by tim-hilt** [comment]
That's great news, thanks for testing :) You can click the "watch"-button at the top to get a notification for when there are new releases. I guess we'll do a new release as soon as #86 is merged, because this might be a problem that a lot of users might have.

**Comment by lumoe** [comment]
Released patch version 1.1.4 that should fix this issue. 

https://github.com/lumoe/obsidian-rollover-daily-todos/releases/tag/1.1.4
