### ISSUE TITLE
Plugin Settings not Visibile

### ISSUE THREAD

**Issue by markthom87** [lumoe/obsidian-rollover-daily-todos#93]
Since a few days the plugin settings are no longer visible. I can press the tab, but the settings window remains empty.

If I install the application as the only one, everything is displayed correctly. After I installed all my other plugins and set settings, the error occurs. Unfortunately, I can't trace the error directly to a specific plugin.

Any Ideas?

![image](https://user-images.githubusercontent.com/16192624/228775036-104f83a3-1550-4a7e-846a-57c338169db1.png)

**Comment by lumoe** [comment]
Can you check whether there are errors in the developer console? 

You can access it via `Ctrl+Shift+i` or `Cmd+Option+i` on MacOS and click on the `Console` tab.

**Comment by markthom87** [comment]
I looked in Console and find this sort of erros. 

[obsidian.md-rollover.log](https://github.com/lumoe/obsidian-rollover-daily-todos/files/11109846/obsidian.md-rollover.log)

**Comment by markthom87** [comment]
Any Idea why isnt work?

**Comment by lumoe** [comment]
To help narrow down the cause, I have a few questions and suggestions:

1. It's possible that your settings file may be corrupted. Are you using any sync services that could have caused this?
2. To eliminate this as a potential cause, please try creating a new, empty vault and install your plugins to see if the issue persists.
3. Can you also provide the Obsidian version you're using?

**Comment by markthom87** [comment]
Okay I found out where the problem is coming from. As soon as I use the Obsidian plugin "Daily Notes" and set my parameters there, the settings become invisible.

Here I also made a mistake, I renamed my template folder some time ago and didn't adjust it there. If you enter a wrong parameter there, then it bangs and your plugin is no longer adjustable.

**Comment by tim-hilt** [comment]
Reopening! I would love this to be fixed first. Changes like renaming a templates folder happen. Our plug-in shouldn’t fail in these cases.

**Comment by markthom87** [comment]
Sounds good. If you need any help or informations just let me know.

**Comment by tim-hilt** [comment]
Found the error: In one place we don't check if the template-file really is available. Therefore, the plugin runs into a `null`-error. I'll submit a PR that fixes this.
