### ISSUE TITLE
Conflict with OneDrive?

### ISSUE THREAD

**Issue by fmge** [lumoe/obsidian-rollover-daily-todos#99]
I cannot run the plugin; unfinished tasks are not transferred. I tried the plugin on another computer where it works. There Obsidian files are stored locally. Is it possible that there is a conflict between the plugin and OneDrive? Thanks for your help!

**Comment by tim-hilt** [comment]
Hi! Even if you’re using OneDrive to sync/backup your files, they are still saved locally. I doubt that OneDrive is the issue in your case.

Can you tell me more about your setup? In particular, the following information would be helpful:

- settings for your daily-notes plugin
- Settings for Obsidian Rollover daily Todos
- are you using the latest version of Obsidian Rollover daily Todos?
- Can you provide a markdown-file where you can reproduce the issue?

**Comment by fmge** [comment]
Thanks for answering!

Settings for your daily-notes plugin:
<img width="835" alt="image" src="https://github.com/lumoe/obsidian-rollover-daily-todos/assets/51640244/efc9e729-7edb-44ba-a7ba-1fe7c2096366">

Settings for Obsidian Rollover daily Todos (it is the latest version):
<img width="822" alt="image" src="https://github.com/lumoe/obsidian-rollover-daily-todos/assets/51640244/ab5d6ff7-2c29-4ab5-9115-9e6ae081edf7">

The provided markdown would be empty due to the fact that the plugin does not transfer todos to the current daily file.

Hope that helps with fixing the issue. Thanks!

**Comment by tim-hilt** [comment]
Maybe it’s a misunderstanding of how our plug-in works: Let me paint the picture for you - then you can tell me if there’s some new information:

1. create yesterdays daily note with todo-items
2. create todays daily note
3. You should see the carried over todos in todays daily note
4. If not: run „roll over todos now“

**Comment by fmge** [comment]
I fully understand how the plugin works. Interestingly, on my working computer it works. But not on my private one. Is there another way for debugging?

**Comment by tim-hilt** [comment]
Sure! You could uninstall obsidian-rollover-daily-todos, clone this repository to your vaults .obsidian/plugins folder, build it via pnpm dev and debug the plugin using the dev-console.

I‘m afraid I can’t provide further help for your specific problem. Ensuring compatibility with all kinds of different setups is out of scope for this plugin.

You could fork the repository and fix the issue you’re having there. If it doesn’t diverge too much from the current code, you could submit a PR!

**Comment by fmge** [comment]
What a pity. Thanks a lot for your help but I will give it up.
